### ISSUE TITLE
Contexts create some unexpected behaviors

### ISSUE THREAD

**Issue by jakelevirne** [digitalocean-appsail/mako#21]
Hello!

I've been playing around with contexts, which seem pretty useful. But I hit a few snags. All these steps were performed in my `nodejs-demo` directory, which contains the sample app, already deployed previously using `mako push` with no context specified.

1. `mako set context staging --app=nodejs-demo --deployment=staging`
    ```
    ✓ 'staging' doesn't exist, OK to create it now: Yes

    Saving Context:
    ---------------

    Context: staging
      App Name: nodejs-demo
      Team: 
      Deployment: staging
    ```
1. `mako push -c staging`
    ```
    ✓ 'staging' doesn't exist, OK to create it now: Yes
    ✓ Would you like to set any environment variables now? (you can edit later if wanted): No
    ```
1. Deploy works well
1. Back in the Dashboard I see two sub-tiles for my "nodejs-demo" app, but at this point nothing really differentiates them, which is confusing.
1. After the deployment finishes, I come back to the Dashboard and now see the two sub-tiles, but one says "Staging", which is really nice.
1. As I navigate around the Dashboard inside the Staging context of my app (e.g. to Env Vars, Settings) I can't tell from the UI that I'm in the Staging context of my app
1. Back in Terminal, I set an environment variable for my app's staging context using `mako set env CONTEXT=stage -c staging`
1. This successfully updates and reloads the app environment, which is great.
1. But now, when I go back to the Dashboard UI, I no longer see the "Staging" label on one of my app sub-tiles. I have to click into both sub-tiles to figure out which one is my Staging context.
1. Once I figure out which is which, I go the Env Vars and I see my new CONTEXT environment variable (hooray!)

**Comment by jonfriesen** [comment]
9. Is fixed in the dashboard now

**Comment by jonfriesen** [comment]
Thanks for the submission, I have changed the way our context works so you shouldn't get any redundant questions. These changes will be in the next release!
