### ISSUE TITLE
deployed app missing from APPS

### ISSUE THREAD

**Issue by laterne** [digitalocean-appsail/mako#24]
An node app I previously deployed is missing from the dashboard. It is still up and running an I see the droplet in my digitalocean account. I tried switching context. Still no app.

The output from `mako get info`

```
     /\       Application : tidy-zucchini-222!
 //\//\\/\\   ---------------------------------------------------
 \\/\\//\//   Live App    : http://tidy-zucchini-222.digioapp.com
 //  \/  \\   Admin       : https://mako.digitalocean.com/go/apps/1adbfbd2-d8b4-4996-a713-a0b62e3c07a7
```

Sometimes during login to the dashboard the following error message appears in the bottom left corner:
![Screenshot from 2020-01-15 19-11-38](https://user-images.githubusercontent.com/3289663/72459514-3973ca80-37cb-11ea-93d3-c4422b45305b.png)

**Comment by jonfriesen** [comment]
Hi @laterne 

Please refer to the answer I provided here: https://github.com/digitalocean-appsail/mako/issues/25
