### ISSUE TITLE
mako renamed sail?

### ISSUE THREAD

**Issue by laterne** [digitalocean-appsail/mako#25]
Is mako and its CLI beeing renamed to sail or am I missing something?

**Comment by jonfriesen** [comment]
Hi @laterne 

We are currently in the process of renaming `Mako` to `App Sail` and the command will be `sail`. We are still working some kinks out of this change.

Unfortunately, we will not be migrating any applications from Mako to the new infrastructure. Your existing apps will continue to exist as droplets in your Digital Ocean cloud account.

We are tirelessly working away at getting this change in place, including new documentation, and some really nice dashboard enhancements! Please stay tuned for more updates :)
