### ISSUE TITLE
Sail update doesn't ask for sudo but fails without it

### ISSUE THREAD

**Issue by eddiezane** [digitalocean-appsail/mako#27]
The update command should prompt for `sudo` or should error that it should be reran with it.

```
 /tmp sail update
Downloading checksum...
Downloading update...
Applying update...

There was an error running the command:

open /usr/local/bin/.sail.new: permission denied
```

**Comment by jonfriesen** [comment]
Hi @eddiezane 

The risk/reward of auto elevating is not worth it and the error message we get is sufficient to direct the user to the solution.

We may add privilege escalation in the future as an external library that handles escalation across all (supported) operating systems.

In addition I have a feeling lots of security people would not be OK with introducing an escalation mid process.

**Comment by eddiezane** [comment]
> the error message we get is sufficient to direct the user to the solution.

I wouldn't say that's the case and that's making assumptions about level of experience. Every single user running `sail update` is going to see this error because of where the file is installed to and the permissions for it.

**Comment by jonfriesen** [comment]
Thanks for bringing up a point that I overlooked with this issue, entry level users. 
I'm improving the error messages:

### Windows
```
You do not have permission to run update as the current user.
Please run again as Administrator.
```

### MacOS/Linux
```
You do not have permission to run update as the current user.
Please run again as "sudo sail update".
```
